#!/bin/bash
# Setup script for email verification environment variables
# This script helps configure SMTP settings for Gmail

echo "=========================================="
echo "Email Verification Setup - Gmail"
echo "=========================================="
echo ""
echo "This script will help you set up environment variables for email verification."
echo ""
echo "Prerequisites:"
echo "1. A Gmail account (or Google Workspace account) for noreply@sequencebiolab.com"
echo "2. 2-Factor Authentication enabled on your Google account"
echo "3. An App Password generated (we'll guide you through this)"
echo ""
echo "=========================================="
echo ""

# Get SMTP username (email)
read -p "Enter your Gmail address (e.g., noreply@sequencebiolab.com or your-gmail@gmail.com): " SMTP_USERNAME
SMTP_USERNAME=${SMTP_USERNAME:-""}

if [ -z "$SMTP_USERNAME" ]; then
    echo "Error: SMTP username is required"
    exit 1
fi

# Get App Password
echo ""
echo "To get your App Password:"
echo "1. Go to: https://myaccount.google.com/apppasswords"
echo "2. Select 'Mail' and your device"
echo "3. Click 'Generate'"
echo "4. Copy the 16-character password (it will look like: xxxx xxxx xxxx xxxx)"
echo ""
read -sp "Enter your Gmail App Password: " SMTP_PASSWORD
echo ""

if [ -z "$SMTP_PASSWORD" ]; then
    echo "Error: SMTP password is required"
    exit 1
fi

# Remove spaces from app password if user included them
SMTP_PASSWORD=$(echo "$SMTP_PASSWORD" | tr -d ' ')

# Get base URL
echo ""
read -p "Enter your application base URL (e.g., https://sequencebiolab.com or http://localhost:5001): " BASE_URL
BASE_URL=${BASE_URL:-"http://localhost:5001"}

# Set defaults
SMTP_HOST="smtp.gmail.com"
SMTP_PORT="587"
SMTP_USE_TLS="true"
SMTP_FROM_EMAIL="noreply@sequencebiolab.com"
SMTP_FROM_NAME="Sequence BioLab"

echo ""
echo "=========================================="
echo "Configuration Summary"
echo "=========================================="
echo "SMTP Host: $SMTP_HOST"
echo "SMTP Port: $SMTP_PORT"
echo "SMTP Username: $SMTP_USERNAME"
echo "SMTP Password: [HIDDEN]"
echo "Use TLS: $SMTP_USE_TLS"
echo "From Email: $SMTP_FROM_EMAIL"
echo "From Name: $SMTP_FROM_NAME"
echo "Base URL: $BASE_URL"
echo "=========================================="
echo ""

read -p "Save these settings? (y/n): " CONFIRM
if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
    echo "Setup cancelled."
    exit 0
fi

# Create .env file
ENV_FILE=".env"
echo "Creating $ENV_FILE file..."

cat > "$ENV_FILE" << EOF
# Email Verification SMTP Configuration
# Generated by setup_email_env.sh
# DO NOT COMMIT THIS FILE TO VERSION CONTROL

export SMTP_HOST="$SMTP_HOST"
export SMTP_PORT="$SMTP_PORT"
export SMTP_USERNAME="$SMTP_USERNAME"
export SMTP_PASSWORD="$SMTP_PASSWORD"
export SMTP_USE_TLS="$SMTP_USE_TLS"
export SMTP_FROM_EMAIL="$SMTP_FROM_EMAIL"
export SMTP_FROM_NAME="$SMTP_FROM_NAME"
export BASE_URL="$BASE_URL"
EOF

# Make .env file readable only by owner
chmod 600 "$ENV_FILE"

echo ""
echo "✅ Environment variables saved to $ENV_FILE"
echo ""
echo "To use these variables, run:"
echo "  source .env"
echo ""
echo "Or add them to your shell profile (~/.bashrc, ~/.zshrc, etc.)"
echo ""
echo "To test the configuration, run:"
echo "  source .env"
echo "  python3 test_email_config.py"
echo ""

